filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /root/.logs/per-diem.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: msg

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
